name: Reusable Workflows
on:
  workflow_call: # Resusable Workflowの定義
    inputs:
      pr-number:
        type: string
        default: ${{ github.event.pull_request.number }}
        requred: false
        description: プルリクエスト番号
    secrets: #  Reusable Workflowではsecretsでトークンを渡す（Actionではinputsを使用した）
      token:
        required: true
        description: GitHubトークン
    outputs:
      message:
        value: ${{ jobs.comment.outputs.pr-comment }}
        description: メッセージ
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: pr-comment
        run: |
          body="Welcome, ${GITHUB_ACTOR}"
          gh pr comment "${PR_NUMBER}" --body "${body}"
          echo "body=${body}" >> "${GITHUB_OUTPUT}"
        env:
          PR_NUMBER: "${{ inputs.pr-number }}"
          GITHUB_TOKEN: ${{ secrets.token }}
    outputs:
      pr-comment: "${{ steps.pr-comment.outputs.body }}"